### ISSUE TITLE
Cache control POST tuloksille

### ISSUE THREAD

**Issue by hvesalai** [tvesalainen/hoski-webapp#1]
Uusimmat mobiiliselaimet (esim. iPad) on ruvennut cachettamaan POST pyynnön tuloksia. Tätä ei ole selaimet aiemmin tehneet, joten siihen ei ole koodissa varauduttu.

Etenkin login-palvelun tulisi asettaa aina Cache-Control headering arvoksi "private, max-age=0, no-cache", jotta login ei lakkaa mystisesti toimimasta.

doPost metodille lisätty 

response.setHeader("Cache-Control", "private, max-age=0, no-cache");

**Comment by tvesalainen** [comment]
Taitaa tämä olla jo hoidettu?
