### ISSUE TITLE
Mapping Request to Servlets

### ISSUE THREAD

**Issue by tvesalainen** [tvesalainen/hoski-webapp#2]
Current web.xml contains mappings like

```
<servlet-mapping>
    <servlet-name>MenuServlet</servlet-name>
    <url-pattern>/member/menu</url-pattern>
    <url-pattern>/races/menu</url-pattern>
</servlet-mapping>
```

Servlet 2.5 specification says:

• A string beginning with a ‘/’ character and ending with a ‘/_’ suffix is used
for path mapping.
• A string beginning with a ‘_.’ prefix is used as an extension mapping.
• A string containing only the ’/’ character indicates the "default" servlet of
the application. In this case the servlet path is the request URI minus the context
path and the path info is null.
• All other strings are used for exact matches only

Current hoski-webapp version 3 accepts

2015-03-10 15:00:39.543 /member/menu?menuKind=Event 200 

When new deployment version 4 (without modifications) doesn't accept it.

**Comment by hvesalai** [comment]
@tvesalainen, do you mean to say that with 

```
<url-pattern>/member/menu</url-pattern>
```

the server gave 404 to

```
/member/menu?menuKind=Event
```

That sounds wrong.

**Comment by tvesalainen** [comment]
Another strange behaviour

/member/keyinfo 200
/races/keyinfo 404

I changed to

```
<servlet-mapping>
    <servlet-name>KeyInfoServlet</servlet-name>
    <url-pattern>/member/keyinfo</url-pattern>
</servlet-mapping>
<servlet-mapping>
    <servlet-name>KeyInfoServlet</servlet-name>
    <url-pattern>/races/keyinfo</url-pattern>
</servlet-mapping>
```

 and it works???

**Comment by hvesalai** [comment]
I think one url-pattern per servlet-mapping is the thing here.

**Comment by tvesalainen** [comment]
Fixed! Will be part of release v4. Can be tested now in:
https://4-dot-hsk-members.appspot.com/member/
https://4-dot-hsk-members.appspot.com/races/
